Permissions: cloud.joinme
CooldownIgnorPermissions: Cloud.JoinMeNoCooldown
PlayerHead: true
NoPermissions: '&c&oI`m Sorry but you don`t have the Permissions!'
line1: '&8&m-------------------------------------------'
line2: '               &f&lNDPCLOUD'
line3: ' '
line4: ' &e%Name% &6plays on &e%Server%'
line5: '  &6Click here to Play with him!'
line6: ' '
line7: '&7your minecraft gameserver manage system'
line8: '&8&m-------------------------------------------'
HoverText: '&6Click to play!'
DisableServerCommand:
- Lobby
- SilentLobby
DisableServerReceive:
- BedWars
- SurvivalGamesETC
DisableServerCommandMessage: '&c&oI`m Sorry but you are not allow to create a JoinMe on Your Server!'
CommandSuccessfullySentMessage: '&a&oYou successfully created a JoinMe.'
CommandCooldownMessage: '&c&oYou have to wait to created a JoinMe.'
PlayerClosedTheJoinMe: '&c&oI´m Sorry but the JoinMe is Closed!'
CommandCooldownMin: 3